# Generated by Django 5.0.3 on 2024-03-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosextras',
            name='bio',
            field=models.CharField(default='', max_length=100),
        ),
    ]
