# Generated by Django 5.0.3 on 2024-03-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('dia', models.DateField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('lugar', models.CharField(max_length=50)),
            ],
        ),
    ]
