# Generated by Django 5.0.3 on 2024-03-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0002_alter_lista_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='datos_extra',
            field=models.CharField(default='', max_length=50),
        ),
    ]
