# Generated by Django 5.0.3 on 2024-03-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0003_lista_datos_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='datos_extra',
            field=models.CharField(default='Nombre', max_length=50),
        ),
    ]
