# Generated by Django 5.0.3 on 2024-03-13 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0004_alter_lista_datos_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista',
            name='imagen',
        ),
    ]
