# Generated by Django 5.0.3 on 2024-03-13 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0005_remove_lista_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='lista',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
