# Generated by Django 5.0.3 on 2024-03-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0006_remove_lista_descripcion_lista_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
