# Generated by Django 5.0.1 on 2024-03-13 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0007_lista_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista',
            name='datos_extra',
        ),
        migrations.RemoveField(
            model_name='lista',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='lista',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='lista',
            name='imagen',
        ),
    ]
