# Generated by Django 5.0.3 on 2024-03-14 03:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0008_remove_lista_datos_extra_remove_lista_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='datos_extra',
            field=models.CharField(default='Nombre', max_length=50),
        ),
        migrations.AddField(
            model_name='lista',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lista',
            name='dia',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='lista',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
