# Generated by Django 5.0.3 on 2024-03-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0009_lista_datos_extra_lista_descripcion_lista_dia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='datos_extra',
            field=models.CharField(default='Nombre por ej.', max_length=50),
        ),
    ]
