# Generated by Django 5.0.3 on 2024-03-14 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0012_alter_lista_datos_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='dia',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
