# Generated by Django 5.0.3 on 2024-03-14 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0014_remove_lista_datos_extra_lista_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lista',
            old_name='nombre',
            new_name='datos_extra',
        ),
    ]
