# Generated by Django 5.0.3 on 2024-03-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0015_rename_nombre_lista_datos_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='datos_extra',
            field=models.CharField(default='Nombre por ej.', max_length=50),
        ),
    ]
