# Generated by Django 5.0.3 on 2024-03-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0017_remove_lista_datos_extra_lista_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='imagen',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
