# Generated by Django 5.0.3 on 2024-03-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0018_alter_lista_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
